### ISSUE TITLE
Send comment summary email for agent when supervisor leaves a comment on a visit

### ISSUE THREAD

**Issue by alqmte** [alqmte/prohealth#10]
After insert comment hook sends E-mail as follows:
   - When agent adds a comment, send an email to his supervisor **_Only if_** visit state is "reviewed".
   - Whenever supervisor adds a comment, send an email to visit owner.

**Comment by alaaOs** [comment]
@AyaMFouad Please be careful when testing this, we don't want to send emails to other people here :D
make sure you change the emails of the visit's agent and supervisor are not real or one of yours
