### ISSUE TITLE
Edit Agent | Tag Documents

### ISSUE THREAD

**Issue by AyaMFouad** [alqmte/prohealth#13]
- [x] Update required expiration date for certain document types
- [x] Add Order attribute to each document type
  - [x] Display Items in sidebar with specfied order
  - [x] Display Items in profile with specfied order
- [x] Print items in specified order, Add Print Option for:
   - [x] Certain Document Type
   - [x] All Documents

**Comment by AyaMFouad** [comment]
@alaaOs  The last page of uploaded file is downloaded twice

**Comment by alaaOs** [comment]
@AyaMFouad done fixed that
