### ISSUE TITLE
Employee Timesheet - Logged

### ISSUE THREAD

**Issue by alqmte** [alqmte/prohealth#9]
- Should be visible until Tuesday midnight * not feasible *
- Should display all visits with the following criteria
  - Verification Status: Verified
  - Chart Status: Completed, Sent to Office
  - Date: less than Sunday midnight before payroll Wednesday

**Comment by alaaOs** [comment]
Done the following:
   1. Added collection **_PayrollSettings_** that has two entries:
       a. payrollDate holds the date of Sunday before payroll Wednesday.
       b. payrollDeadline holds the date of payroll Wednesday.
   2. Added a cronjob that runs every week, checks if two weeks have passed from the last payroll.
       and updates PayrollSettings if the condition is met.
   3. Added the field formDate to the subscription query in timesheet.js  to load only visits before Monday
       of payroll week.
   4. Added a check if today == payroll Wednesday don't show timesheet.
   5. Added /setPayroll to set the date manually.
